name: Build (iOS/tvOS)

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: iOS, archflag: -arch arm64, sdk: iphoneos, triplet: arm64-ios }
        - { name: iOS Sim ARM64, archflag: -arch arm64, sdk: iphonesimulator, triplet: arm64-ios-simulator }
        - { name: tvOS, archflag: -arch arm64, sdk: appletvos, triplet: arm64-tvos }
        - { name: tvOS Sim ARM64, archflag: -arch arm64, sdk: appletvsimulator, triplet: arm64-tvos-simulator }

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: CMake Configure
        run: >
          cmake -B build -G Xcode
          -DFT_REQUIRE_PNG=ON
          -DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=1
          -DCMAKE_DISABLE_FIND_PACKAGE_BZip2=1
          -DCMAKE_DISABLE_FIND_PACKAGE_BrotliDec=1
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.platform.triplet }}
          -DCMAKE_C_FLAGS=-m${{ matrix.platform.sdk }}-version-min=11

      - name: Build
        run: |
          xcodebuild -project build/freetype.xcodeproj -target freetype ${{ matrix.platform.archflag }} only_active_arch=no -configuration Release -sdk ${{ matrix.platform.sdk }} clean build

      - uses: actions/upload-artifact@v4
        with:
          name: FreeType Artifacts ${{ matrix.platform.name }}
          path: build/Release/*.a
